### ISSUE TITLE
Can you also run x86_64 Linux programs?

### ISSUE THREAD

**Issue by theoretischer** [Ilya114/Box64Droid#102]
And if not are there any alternatives?

**Comment by Ilya114** [comment]
Pretty hard

**Comment by wisplite** [comment]
I feel like this shouldn't be closed. Maybe I misunderstand how this works, but isn't this an x86_64 translation layer just running the x86 version of Wine, a Linux application, to emulate a Windows environment? I'd imagine it would be significantly better to bypass the Windows layer and run native Linux applications through just one layer of emulation, not two.

**Comment by AnotherNeko** [comment]
I really want to run linux amd64 apps on my android phone
