### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by weaster007** [Ilya114/Box64Droid#104]
Hello, I tried box64droid and I love that it supports mouse input with a hardware mouse.
Does anybody know how to get the same in winlator?
In winlator I can only drag the mouse like a touch screen. 

I hope anyone can help me. Would be awesome. 

Thanks a lot and keep it up ;)

**Comment by Ilya114** [comment]
@weaster007 Here only Box64Droid supporting, no Winlator
