### ISSUE TITLE
How to center screen?

### ISSUE THREAD

**Issue by AhmetHasanAkkoca** [Ilya114/Box64Droid#105]
Hello, how to center the screen?
It is aligned at left upper corner.
And is there any way to eliminate error 9 other than adb(or without computer)?

Thanks

**Comment by Ilya114** [comment]
You cant center screen, just set same resolution in termux-x11 and box64droid

**Comment by AhmetHasanAkkoca** [comment]
But then the rounded corners are the problem

**Comment by Ilya114** [comment]
> But then the rounded corners are the problem

Can you show?

**Comment by AhmetHasanAkkoca** [comment]
I reinstalled box64droid after adb shell code (Problem 9) and selected 1920x1080 in both termux and termux:x11(resolution mode:exact) and now it is centered and working correctly👍
![Screenshot_20240215-212440](https://github.com/Ilya114/Box64Droid/assets/66252973/eb76e066-3b01-47f4-8d8c-e98a7278864f)

**Comment by Ilya114** [comment]
So can close
