### ISSUE TITLE
After changing Wine Not usable

### ISSUE THREAD

**Issue by Luihart** [Ilya114/Box64Droid#11]
My steps:
Start-box-root
Choose Resolution
Change Wine Version
Box86
Stable
6.0
Run box86

Explorer is empty, No TFM, Drives, cant use anything, start Menu is empty

Second step:
Update system
Update box86/64

Result: issue still there
![Screenshot_2023-05-08-00-44-26-834_com termux x11](https://user-images.githubusercontent.com/97235637/236706257-799ad5b0-b61c-4b04-8a65-406bd0435c03.jpg)

 - Device: Poco F3
 - OS: Android 13
 - Termux version 0.118

**Comment by Ilya114** [comment]
Wjne 6.0 may be not work

**Comment by Ilya114** [comment]
Wine 6.0 working fine for me

**Comment by Luihart** [comment]
Hm OK i will try to Switch to another Wine Version and See If its working again.

**Comment by Ilya114** [comment]
> Did you try it on chroot too?

Did, Wine version changing correct.

----
I'm found box64 not has -DBAD_SIGNAL=ON parameter when updating (recompile), so not recommend to update now

**Comment by Ilya114** [comment]
> Chroot May Not stopping box86/64 correctly Like proot.

Reboot phone will unmount all mountpoints

**Comment by Luihart** [comment]
> > Chroot May Not stopping box86/64 correctly Like proot.
> 
> Reboot phone will unmount all mountpoints

Thx i will keep that in mind, and Test this after a Crash again. Happened to me already 5 Times, but i could revive it with Update Box so Far. But this time nope.

**Comment by Luihart** [comment]
Fixed after reinstall completely Termux. Wine 6.0 working and it installed automatically DXVK and Drive D mount. Great Job! Getting better and better
