### ISSUE TITLE
Start menu options all broken

### ISSUE THREAD

**Issue by guyman624** [Ilya114/Box64Droid#110]
Using latest box64droid, ran the update script, issue persists.

Android 14, OnePlus 12R

All buttons in the start menu pull up the same error about there being no program to open lnk files.
![Screenshot_2024-03-11-16-38-36-08_00df01c412509efb9bd6450c382822af](https://github.com/Ilya114/Box64Droid/assets/82007920/dfbda7ed-617b-4368-8bbb-afc7c4e92a56)

**Comment by Ilya114** [comment]
Reinstall

**Comment by guyman624** [comment]
Thank you, fresh reinstall fixed issue!
