### ISSUE TITLE
memory allocating trouble

### ISSUE THREAD

**Issue by twinflac** [Ilya114/Box64Droid#115]
MESA: error: zink: DEVICE LOST!
MESA: error: ZINK: vkMapMemory failed (VK_ERROR_MEMORY_MAP_FAILED)
8948|SIGSEGV @0x7abf4466b0 (???(/usr/local/lib/aarch64-linux-gnu/dri/zink_dri.so+0x7666b0)) (x64pc=0x14ff3/???:"???", rsp=0x1007fe2b8, stack=0x100000000:0x100800000 own=(nil) fp=0x1007fe4c0), for accessing 0x38 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000007ab4283010 RSP-0x18:0x0000000000000000 RSP-0x10:0x0000000000000001 RSP-0x08:0x00000000650fcf90
RSP+0x00:0x00000000017a315f RSP+0x08:0x00000001007fe410 RSP+0x10:0x0000000001e6a549 RSP+0x18:0x00000001007fe358
RAX:0x0000000000000500 RCX:0x0000000000000168 RDX:0x0000000000000280 RBX:0x00000000683d52d0
RSP:0x00000001007fe2b8 RBP:0x00000001007fe4c0 RSI:0x0000000000000000 RDI:0x0000000000000000
 R8:0x0000000000000000  R9:0x0000000000000000 R10:0x00000000656cf240 R11:0x0000000000000002
R12:0x00000000683d5244 R13:0x0000000067010fc0 R14:0x0000000000000001 R15:0x00000000683d5244
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053
Segmentation fault

**Comment by Ilya114** [comment]
you need set env var to work on adreno 630

**Comment by twinflac** [comment]
what env i need to set?

**Comment by Ilya114** [comment]
in /sdcard/Box64Droid/Box64Droid.conf add `export MESA_VK_WSI_DEBUG=sw`

**Comment by twinflac** [comment]
thx
