### ISSUE TITLE
Werid IPV4/DNS issue

### ISSUE THREAD

**Issue by Jacobw1oo** [Ilya114/Box64Droid#116]
So Wine 9.1 on Native mode, i have installed Steam and Firefox. 
Ping works at start, then after turn on any internet thing, it breaks. No more Ping, no internet.

Android 13 - Non Rooted

**Comment by Ilya114** [comment]
phone?

**Comment by Jacobw1oo** [comment]
yes, RedMagic 8S

**Comment by Jacobw1oo** [comment]
Additional Installing internet explorer 8 fixes it, but then your forces on windows 2003. which both Steam and Firefox refuse to start

**Comment by Jacobw1oo** [comment]
it comes from the Glibc, i install Pipetto-crypto/androBox and it has the same issue.

**Comment by Ilya114** [comment]
> it comes from the Glibc - prefix, i install Pipetto-crypto/androBox and it has the same issue.

So if problem in glibc-pref i cant help with that, well for me all fine

**Comment by natpauze** [comment]
Hey @Jacobw1oo , i'm facing a similar issue, pings work but no actual requests succeed in the wine box64/86 environment. Did you find a fix that worked for you?

**Comment by Jacobw1oo** [comment]
> Hey @Jacobw1oo , i'm facing a similar issue, pings work but no actual requests succeed in the wine box64/86 environment. Did you find a fix that worked for you?

I did not find a fix, i had to avoid that entire glibc, which did not leave me with much. mobox works ( cant install mono), otherwise i use a Proot.
