### ISSUE TITLE
Nothing appears in Termux X11

### ISSUE THREAD

**Issue by SombraShadow** [Ilya114/Box64Droid#12]
**Describe the bug**

I normally start box64 through termux and when I enter Termux x11 nothing appears (In other previous versions of the script this did not happen)

**To reproduce**

- Enter Termux and type "start-box", choose the resolution (I choose 800x600) and start box64

**Screenshots**
<details>

![Screenshot_20230507-190052](https://user-images.githubusercontent.com/86113002/236706770-e0976706-8d7b-482e-9107-7d5e2df60220.png)
![Screenshot_20230507-190100](https://user-images.githubusercontent.com/86113002/236706882-7a627082-8927-405d-ae0f-6ee3be424515.png)
![Screenshot_20230507-190116](https://user-images.githubusercontent.com/86113002/236706887-d0166d67-0a8c-49ea-932d-6c2882da5103.png)
</details>

And when I try to stop box64, as soon as I try to use "ctrl c" + 1 to stop,box64 doesn't stop.

**Smartphone:**

 - Device: Motorola Moto G9 Plus
 - OS: Android 11
 - Termux version: 0.118

**Comment by seven768** [comment]
Same problem

**Comment by SombraShadow** [comment]
Well, I managed to solve the problem after cleaning the Termux data and installing it again.

**Comment by seven768** [comment]
Still not working for me(

**Comment by Ilya114** [comment]
> Still not working for me(

Did you use root or proot version? I know you have root

**Comment by seven768** [comment]
Proot version have black screen, root version not working...
![Uploading Screenshot_2023-05-08-13-53-33-780_com.termux.jpg…]()

**Comment by seven768** [comment]
![Screenshot_2023-05-08-13-53-33-780_com termux](https://user-images.githubusercontent.com/72708624/236783059-7847d064-3461-4f55-8877-6adeb68cb186.jpg)

**Comment by Ilya114** [comment]
Please use 

<dеtails>

image
</dеtails>

when attaching images. Back to your problem seems Termux-X11 not started. Try start manually: `Xvfb :0 -ac && DISPLAY=:0 termux-x11`

**Comment by seven768** [comment]
Not working unfortunately. But Box86 works fine, only Box64 have black screen

**Comment by Ilya114** [comment]
> Not working unfortunately. But if i choose Box86 that it works fine, only Box64 have black screen

Last version?

**Comment by Ilya114** [comment]
> Well, I managed to solve the problem after cleaning the Termux data and installing it again.

So can close ticket
