### ISSUE TITLE
Mesa info request

### ISSUE THREAD

**Issue by Jacobw1oo** [Ilya114/Box64Droid#127]
i am on the chrooted version, installed xfce4 it was running fine. The Mesa driver has been having issues, first the anti flick fix has not been applied, second dri3 patch does not seem to be applied. Over all stability has been struggling, i cant completed a glmark2 test, glxgears will freeze after 15 secs. any GPU stress test causes it to freeze. Any information on where the special mesa drivers are, and if your going to tell me about the compile please be clear on instructions (i have spent like 30 hours on compiling mesa and never get a working driver).

**Comment by Jacobw1oo** [comment]
![Screenshot_2024-07-13_13-35-27](https://github.com/user-attachments/assets/3789e770-ab19-4721-9d89-60c6fb4a5265)

Screenshot from device

**Comment by Ilya114** [comment]
Chroot in main outdated, we are using native version

**Comment by Jacobw1oo** [comment]
None of the Native version work for me. your glibc DNS is broken on mine.

**Comment by Jacobw1oo** [comment]
i have found the fix, and I will be building a new Ubuntu root.

Commands:
#upgrading for 22 to 24
echo"current version"
lsb_release -a
read -p "Press enter to attempt distro upgrade"
do-release-upgrade -d
echo"current version"
lsb_release -a
echo "it should be 24.04 noble"
read -p "Press enter to continue"

#Mesa Update (only Ubuntu 24 is supported)
apt-get install software-properties-common
add-apt-repository ppa:mastag/mesa-turnip-kgsl
apt update
apt upgrade
