### ISSUE TITLE
BioShock (2007) takes too much time to load, and crashes at the first 3D scene

### ISSUE THREAD

**Issue by yuraPIMENOV** [Ilya114/Box64Droid#13]
The game BioShock (2007) takes too much time to boot up (5-7 min), the intro level also takes too much time to load, and then crashes.
Device: Mi Pad 5 (SD860), Android 13, MIUI 14

**Comment by Ilya114** [comment]
this happens when the game is not moved to drive C:

**Comment by yuraPIMENOV** [comment]
> this happens when the game is not moved to drive C:

I installed the game to C:, launched it with -dx9 - but it still boots up as slow as GTA 5 without SSD, and crashes when I click 'New Game'.

**Comment by Ilya114** [comment]
I dont know, maybe proot problem
