### ISSUE TITLE
Desktop environment doesn't seem to be start

### ISSUE THREAD

**Issue by Boring-student** [Ilya114/Box64Droid#14]
**Describe the bug**

Winehq should have started the virtual desktop but in this case it doesn't seem to be. Which gives only black screen.

**To reproduce**

- Install as normal. (doesn't matter if it root or not both have the same issues.)
- start either box86 or box64 (technically this should start virtual desktop now)
- Ctrl+C then enter to access the terminal
- start a program with "box86 wine [program executable]"

**Screenshots**

<details>

![Screenshot_20230508-233739_Termux_X11.png](https://user-images.githubusercontent.com/74827801/236882210-6d40dd7f-2d3e-441a-a8fe-a9e52cdd0b13.png)

![Screenshot_20230508-233904_Termux_X11.png](https://user-images.githubusercontent.com/74827801/236882226-7cb6b4df-460c-46be-ba67-0666de43ab70.png)

</details>

**Smartphone:**

 - Device: Samsung A71
 - OS: Pixel Experience Plus 13
 - Termux version 0.118

**Comment by Boring-student** [comment]
> > Winehq should have started the virtual desktop but in this case it doesn't seem to be. Which gives only black screen.
> 
> Did you change Wine version? And why you need Firefox on Box86 or Box64

1.I didn't change it yet

2.I just need a program to to test my assumption and it's only 379Kb

**Comment by Ilya114** [comment]
Try: `box86 wine explorer /desktop=shell,800x600 /opt/TFM`

**Comment by Boring-student** [comment]
> Try: `box86 wine explorer /desktop=shell,800x600 /opt/TFM`

Assuming this will make a permanent solution?

>WINEPREFIX=box64 wine explorer /desktop=shell,1280x720 /opt/TFM

**Comment by Ilya114** [comment]
> Assuming this will make a permanent solution?

? It's working?

**Comment by Boring-student** [comment]
> > Assuming this will make a permanent solution?
> 
> ? It's working? 

It should but it can't find wine

But the wine command is worked

<details>

![Screenshot_20230509-005836_Termux.png](https://user-images.githubusercontent.com/74827801/236896908-41449d23-ca93-4970-a385-1102ae2a4553.png)

</details>

**Comment by Ilya114** [comment]
You just not using box64. Full command:
`WINEPREFIX=/root/.wine-amd64 box64 wine explorer /desktop=shell,800x600 /opt/TFM`

**Comment by kryptous** [comment]
I have the same problem of box64 desktop not starting.

I input that into the start file located at 
/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/opt


![Screenshots_2023-05-08-14-36-44](https://user-images.githubusercontent.com/88349838/236916878-5db2357a-783e-4ae1-9ec9-30a5c5d55b31.png)

 then I get the resulting error 

![Screenshot_20230508-143753](https://user-images.githubusercontent.com/88349838/236917058-6043ad2e-093f-40b3-bb2a-2d629bdc07c4.png)


How can I fix this?

**Comment by Ilya114** [comment]
> How can I fix this?

Reinstall

**Comment by Ilya114** [comment]
Closing due a not activity

**Comment by Waterdish** [comment]
I fixed this by making box64 call wine64 instead of just wine in /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/opt.
So it would be
WINEPREFIX=/root/.wine-amd64 box64 wine64 explorer /desktop=shell,800x600 /opt/TFM
