### ISSUE TITLE
Box64droid not installing 

### ISSUE THREAD

**Issue by heeeeeeeeeeh** [Ilya114/Box64Droid#15]
**Describe the bug**

I get an error when trying to run the install command 

**To reproduce**

- run install command -curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install

**Screenshots**

<details>

![Screenshot_20230508-171751.png](https://user-images.githubusercontent.com/90989842/236950469-5b0b77af-35b5-4f1f-ab68-b21b6096106b.png)

</details>

**Smartphone (please complete the following information):**

 - Device: Nokia x100 5g
 - OS:  Android 11
 - Termux version 0.118

**Comment by Ilya114** [comment]
Clear Termux data and try again

**Comment by Luihart** [comment]
> **Describe the bug**
> 
> I get an error when trying to run the install command
> 
> **To reproduce**
> 
>     * run install command -curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install
> 
> 
> **Screenshots**
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: Nokia x100 5g
> 
>     * OS:  Android 11
> 
>     * Termux version 0.118

Ya Sometimes when you Reinstall it needs two Times Installation too, until it works correctly
