### ISSUE TITLE
Error when using chroot version. Will not start

### ISSUE THREAD

**Issue by inguna87** [Ilya114/Box64Droid#16]
After I run start-box-root command and choose resolution I get this error and box will not start
![Screenshot_20230509-123404](https://github.com/Ilya114/Box64Droid/assets/103364968/bfebc087-5db8-418b-8c3d-86c862d62c6f)
Android 10
Root Magisk 23
Oneplus 7 Pro
Latest Box64Droid version. After clean install

**Comment by Ilya114** [comment]
Seems Termux-x11 not started correctly

**Comment by inguna87** [comment]
I changed 
"sudo chroot $ROOTFSPATH /bin/su - root" to "sudo chroot $ROOTFSPATH /bin/su" in start-box-root script file and now it start normally.

**Comment by Ilya114** [comment]
> I changed
> "sudo chroot $ROOTFSPATH /bin/su - root" to "sudo chroot $ROOTFSPATH /bin/su" in start-box-root script file and now it starts normally.

Thanks, will add to start script

**Comment by Ilya114** [comment]
> I changed "sudo chroot $ROOTFSPATH /bin/su - root" to "sudo chroot $ROOTFSPATH /bin/su" in start-box-root script file and now it starts normally.

Well, after testing I have problem with `su`, so using `su -`
