### ISSUE TITLE
Termux won't connect to raw.githubusercontent.com

### ISSUE THREAD

**Issue by KintCark** [Ilya114/Box64Droid#17]
When I try to install this:curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install

It give me error 
![Screenshot_20230511-011353](https://github.com/Ilya114/Box64Droid/assets/101164907/9efe9400-b7d0-4cb7-a31f-c684e266161c)

Can you fix the link?

 - Device: [Motorola g edge 2021]
 - OS: [e.g. Android 12]
 - Termux version [e.g. 0.118]

**Comment by Ilya114** [comment]
Yiu
