### ISSUE TITLE
Poco F1 black screen

### ISSUE THREAD

**Issue by heckerarm** [Ilya114/Box64Droid#18]
- Device: [Xiaomi POCO F1]
 - OS: [Android 10]
 - Termux version [0.118]

 I just see a black screen, in box64
![IMG_20230512_202017_070](https://github.com/Ilya114/Box64Droid/assets/80280426/be88e155-c050-4526-a9cc-23b17fb6e613)

**Comment by Waterdish** [comment]
How did you fix this?
