### ISSUE TITLE
A problem that occurred in chroot.

### ISSUE THREAD

**Issue by Beyond121** [Ilya114/Box64Droid#20]
**Describe the bug**

Attempting to run programs that are not yet compatible with box64 in chroot can result in one of two situations: 1. box64 encounters a strange problem that prevents it from starting normally again (it always displays as a black screen in x11 and the entire program must be reinstalled). 2. The phone crashes directly and automatically restarts after a period of time.
I am not sure if all incompatible programs will cause this problem, but it has been confirmed that programs that do cause this problem will not have the same issue in proot (they will only crash). This problem seems to occur more easily in Unity games.

This passage was translated using machine translation. Please forgive me if there are any inaccuracies.

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: one plus 9
 - OS: Android11 ColorOS11.2
 - Termux version：0.118

**Comment by Ilya114** [comment]
And what I should do?

**Comment by Beyond121** [comment]
Is this issue fixable? Accidentally running an incompatible program and causing the phone to shut down is always scary.

I just want to mention, if this is not the right place to give feedback then I’m truly sorry.

**Comment by Ilya114** [comment]
Unity can working bad
