### ISSUE TITLE
Memory access

### ISSUE THREAD

**Issue by SolusMonahus** [Ilya114/Box64Droid#23]
**Describe the bug**

If you set the value to BOX64_DYNAREC=0 , access to memory is lost. box64droid proot.

**To reproduce**

- Try '...'

**Screenshots**
![Screenshot_20230516-000038_Termux_X11](https://github.com/Ilya114/Box64Droid/assets/113862634/4b4a3699-d3a6-4ab6-ae52-a9f15039e9c9)

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: OnePlus 9r
 - OS: Android 13 custom & magisk
 - Termux version 0.118

**Comment by Ilya114** [comment]
Don't disable Dynarec
