### ISSUE TITLE
proton

### ISSUE THREAD

**Issue by SolusMonahus** [Ilya114/Box64Droid#25]
**Describe the bug**

Games with Wine Proton won't start. Chroot.

**To reproduce**

- Try '...' 

**Screenshots**
![Screenshot_20230518-115000_Termux_X11](https://github.com/Ilya114/Box64Droid/assets/113862634/c927cd4b-e8d3-4bab-98eb-03f7e45fc942)

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: OnePlus 9r 12/256
 - OS: custom Android 13 & magisk
 - Termux version 0.118

**Comment by Ilya114** [comment]
Well, try change Wine version. I don't know about games

**Comment by SolusMonahus** [comment]
@Ilya114 items disappear from start menu when changing wine input bridge and dxvk

**Comment by SolusMonahus** [comment]
@Ilya114 also after changing the wine the error did not disappear anywhere, nothing works

**Comment by Luihart** [comment]
Changing Wine works for me only after a reboot of box64. But since your Wine is now corrupted you need to Reinstall anyway

**Comment by SolusMonahus** [comment]
Games started working after I installed d3dcompiler

**Comment by SolusMonahus** [comment]
@Ilya114  can you please give me a link to install the old version chroot?
