### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by sunnyhenry123** [Ilya114/Box64Droid#26]
I'm sorry but I'm greenhand.
How to change the system language?
I tried `export LANG=zh_CN.UTF-8` but not working.

**Comment by Ilya114** [comment]
You need to run `dpkg-reconfigure locales` then configure need locale then change `export en_US.UTF-8` to need locale in `~/.bashrc`, should be work

**Comment by sunnyhenry123** [comment]
`~ $ apt install locales
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package locales`

**Comment by Ilya114** [comment]
> `~ $ apt install locales Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package locales`
You trying it in Termux, not Box64Droid. And locales already installed

**Comment by sunnyhenry123** [comment]
> > `~ $ apt install locales Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package locales`
> 
> You trying it in Termux, not Box64Droid. And locales already installed

How can I opreate it in box64droid?
After start-box, I can only enter 1-7 and resolution.

**Comment by Ilya114** [comment]
> After start-box, I can only enter 1-7 and resolution

You can just press ctrl+c

**Comment by lsl330** [comment]
> I'm sorry but I'm greenhand. How to change the system language? I tried `export LANG=zh_CN.UTF-8` but not working.

我建立了Box64Droid-For-Chinese项目，跟着说明运行脚本可以很轻易配置成中文

**Comment by Ilya114** [comment]
> 我建立了Box64Droid-For-Chinese项目，跟着说明运行脚本可以很轻易配置成中文

Thank you for your tool, but in case people have problems with it, I'm not responsible for it for them
