### ISSUE TITLE
Box64Droid chroot wont close completley

### ISSUE THREAD

**Issue by FTKCET** [Ilya114/Box64Droid#27]
Hello im facing a problem.
Box64Droid on Chroot wont close and stays inside the ram.
Ive tried ctrl+c +1 + exit but it stays in the ram and it wont open anymore.
After a reboot it works. Please fix it.
Samsung Galaxy S10 Lite.

**Comment by Ilya114** [comment]
I have nothing to fix. Send screenshots with your problems

**Comment by kryptous** [comment]
I have been having this same problem and this is how I fixed it:

In termux type: 
`start-box-root`

type option 1

type desired resolution e.g 800x600

press control + c

Enter command to stop chroot in background:
`box64 wineserver -k`

Enter command to start desktop in termux-x11:
`taskset -c 4-7 box64 wine explorer /desktop=shell,$res /opt/TFM`

**Comment by FTKCET** [comment]
Thank you very much it worked.
Now it shows 4,5gb ram available instead of 3,5

**Comment by Ilya114** [comment]
> Ive tried ctrl+c +1 + exit but it stays in the ram and it wont open anymore.

Well, you should press ctrl-c+1 withiut exit

**Comment by Ilya114** [comment]
I improved exit, try again, should be closing completely

**Comment by FTKCET** [comment]
works now.....thank you...
