### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by guranu** [Ilya114/Box64Droid#29]
**Describe the bug**

Black screen when trying to launch box64 on termux x-11

**To reproduce**

- Install it normally
- press 1
- add resolution (in my case it was 1280x1024)

**Screenshots**
<details>

![Screenshot_20230519-111223](https://github.com/Ilya114/Box64Droid/assets/103632948/539dae15-4903-4c63-b0e5-db47175f63a5)
![Screenshot_20230519-111547](https://github.com/Ilya114/Box64Droid/assets/103632948/f4261120-ec36-41f2-8bcb-98d374b1eb79)
</details>

**Smartphone (please complete the following information):**

 - Device: Oneplus 7
 - OS: Android 10
 - Termux version 0.118.0

**Comment by Ilya114** [comment]
> > 
> 
> But i don't have root on the device and android 11 is awful on oneplus 7 is there an alternative way to run this on android 10 without root?

No.

**Comment by guranu** [comment]
Well fuck me then.

**Comment by simus1** [comment]
![Screenshot_2023-05-19-17-30-25-492_com termux](https://github.com/Ilya114/Box64Droid/assets/134063283/179e8aa1-a5ba-4795-9574-9bec8a1cbb1a)
![Screenshot_2023-05-19-17-30-25-492_com termux](https://github.com/Ilya114/Box64Droid/assets/134063283/2d13cc08-5691-4b63-b028-54cae665b6ff).    Mine is freeze
