### ISSUE TITLE
start-box-root leads to mounting error

### ISSUE THREAD

**Issue by Luihart** [Ilya114/Box64Droid#3]
Hi Ilya,
Does chroot Work?
Poco F3 8GB/256GB
Miui14/ Android 13

If i Type start-box-root i get this (granted root Access of course)

Termux-x11 started.                                     mount: mounting /dev on /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/dev failed: No such file or directory                                  mount: mounting /sys on /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/sys failed: No such file or directory                                  mount: mounting /proc on /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/proc failed: No such file or directory                                mount: mounting devpts on /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/dev/pts failed: No such file or directory                            mount: mounting /sdcard on /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/sdcard failed: No such file or directory                            mount: mounting /data/data/com.termux/files/tmp on /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/tmp failed: No such file or directory       chroot: can't change root directory to '/data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu': No such file or directory                            umount: can't unmount /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/dev/pts: No such file or directory                                       umount: can't unmount /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/dev: No such file or directory                                           umount: can't unmount /data/data/com.termux/files/var/lib/proot-distro/installed-rootfs/ubuntu/proc: No such file or directory

**Comment by Ilya114** [comment]
Fixed, try again

**Comment by Luihart** [comment]
OK, now i get this:

Termux-x11 started.                                     mount: mounting /dev on /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev failed: No such file or directory                              mount: mounting devpts on /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev/pts failed: No such file or directory                        mount: mounting /sdcard on /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/sdcard failed: No such file or directory
su: cannot set groups: Operation not permitted
umount: can't unmount /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev/pts: No such file or directory                                   umount: can't unmount /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev: No such file or directory

**Comment by Coldboy195** [comment]
start-box-root

![Screenshot_2023-05-03-21-33-39-283_com termux](https://user-images.githubusercontent.com/105062195/235948502-11af35e9-0e58-4436-975c-a43733338263.jpg)

**Comment by Ilya114** [comment]
> start-box-root
> 
> ![Screenshot_2023-05-03-21-33-39-283_com termux](https://user-images.githubusercontent.com/105062195/235948502-11af35e9-0e58-4436-975c-a43733338263.jpg)

Install busybox

**Comment by Ilya114** [comment]
> OK, now i get this:
Redownload `start-box-root`, then:
```
mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev

mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/sys

mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/proc

mkdir /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/dev/pts
```
then: `start-box-root`

**Comment by Ilya114** [comment]
And so, chroot is not yet stable and is not recommended for use, startup scripts work but there is no Internet and there are problems with rights. If I decide problems, let you know

**Comment by Ilya114** [comment]
Hi, I fixed chroot, now you can try install and test again

**Comment by Luihart** [comment]
Great. OK i will Test, i will reinstall complete since updating system/Box was Not enough. (Start-box-root command Not found)
