### ISSUE TITLE
[FEATURE REQUEST] Make the installation process more verbose 

### ISSUE THREAD

**Issue by nesper8** [Ilya114/Box64Droid#30]
The reason for this feature request is for the more non tech initiated people. This feature request will  give people a piece of mind without being worried that the installation process has crashed.

A simple progress bar itself would be best for users to know how much the progress of the installation is

**Comment by Ilya114** [comment]
Okay

**Comment by Ilya114** [comment]
Done

**Comment by nesper8** [comment]
Thank you
