### ISSUE TITLE
gta 5 dxvk 2.2 either crashing or freezing at startup(((

### ISSUE THREAD

**Issue by yuraPIMENOV** [Ilya114/Box64Droid#33]
somebody ran gta5 on sd860 using dxvk 2.1/2.2 but on my mipad5 it freezes at r* logo((((((((((((((
my game is build 1868 with goldberg's crack (xatab repack)
how can i fix it? on my pc it runs fine

**Comment by Ilya114** [comment]
I dont know how to fix it.
