### ISSUE TITLE
bioshock playable fps but takes too much time to boot up(((

### ISSUE THREAD

**Issue by yuraPIMENOV** [Ilya114/Box64Droid#34]
Bioshock (original, not remaster) v1.1, no mods, runs quite playable (15-20fps) after removing DXVK but the boot up takes an extremely long time (the logo hangs for 5-7 minutes, the screen with the level title hangs for half an hour), how can i reduce the waiting time? i really want to play bioshock on my mobile, not on pc, but on exagear it freezes at startup on all midrange snapdragon socs, on skyline it crashes every minute, and the j2me/brew versions are crappy and very stupid(((

**Comment by Ilya114** [comment]
Root will help you
