### ISSUE TITLE
I don't understand how to install this software.

### ISSUE THREAD

**Issue by JackJollimore** [Ilya114/Box64Droid#36]
Hello,  my device is a Samsung s10+

I run the command for a rootless installation,

curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install

Here is the output: 

Starting installation, please wait...
-e  Box64Droid creates a folder called Box64Droid at the internal storage to store configuration files. For Termux to create this folder, it is necessary to have storage permissions, click on allow to proceed (or deny and press CTRL + c to cancel the installation).

It appears that directory '~/storage' already exists.
This script is going to rebuild its structure from
scratch, wiping all dangling files. The actual storage
content IS NOT going to be deleted.

Aborting configuration and leaving directory '~/storage' intact.                                                      Checking availability of current mirror:                   [*] https://mirrors.utermux.dev/termux/termux-main: ok
Hit:1 https://its-pointless.github.io/files/21 termux InRelease
Hit:2 https://mirrors.utermux.dev/termux/termux-main stable InRelease
Hit:3 https://mirrors.utermux.dev/termux/termux-x11 x11 InRelease                                                     Reading package lists... Done                              Building dependency tree... Done
Reading state information... Done
All packages are up to date.
-e
-e  Installing x11-repo...
-e
-e  x11-repo installed.

-e  Installing need packages...

-e  Downloading and installing the Termux-x11 package...
-e
-e  Termux-x11 installed.

-e  Checking for other rootfs and removing them if any
-e
-e  Downloading preconfigured rootfs...
-e
rm: cannot remove '/sdcard/Box64Droid': No such file or directory
--2023-05-20 12:51:57--  https://github.com/Ilya114/Box64Droid/raw/main/apps/termux-x11-1.02.07-0-all.deb
(Reading database ... 23316 files and directories currently installed.)
Preparing to unpack termux-x11-1.02.07-0-all.deb ...
Unpacking termux-x11 (1.02.07-0) over (1.02.07-0) ...
Checking availability of current mirror:
[*] https://mirrors.utermux.dev/termux/termux-main: Checking availability of current mirror:
[*] https://mirrors.utermux.dev/termux/termux-main: Setting up termux-x11 (1.02.07-0) ...
140.82.112.3
Connecting to github.com|140.82.112.3|:443... connected.
HTTP request sent, awaiting response...
Error: distribution 'ubuntu' is not installed.

ok
ok
302 Foundackage lists... 0%
Location: https://raw.githubusercontent.com/Ilya114/Box64Droid/main/apps/termux-x11-1.02.07-0-all.deb [following]
--2023-05-20 12:51:58--  https://raw.githubusercontent.com/Ilya114/Box64Droid/main/apps/termux-x11-1.02.07-0-all.deb
Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
x11-repo is already the newest version (8.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
HTTP request sent, awaiting response... 200 OK
Length: 5530 (5.4K) [application/octet-stream]
Saving to: ‘termux-x11-1.02.07-0-all.deb.1’

termux-x11-1.0 100%   5.40K  --.-KB/s    in 0s

2023-05-20 12:51:58 (40.2 MB/s) - ‘termux-x11-1.02.07-0-all.deb.1’ saved [5530/5530]

Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by pWaiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 11775 (apt)

The installer continues by downloading and then after finishing the download;

Install finished. To start Box86 and Box64 type 'start-box'
-e
-e  And if everything goes as planned, the Wine environment will start and soon after TFM will open, that's it.

-e  When stopping using the x11 server, it is recommended to force stop Termux through the settings. You can also use the 'kill' command + the Termux-X11 pid(type termux-x11, and at the end the id will appear)

-e  That's all.
mkdir: cannot create directory ‘/data/data/com.termux/files/usr/var/lib/proot-distro/’: File exists
mkdir: cannot create directory ‘/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/’: File exists
chmod: cannot access 'start-box': No such file or directory
--2023-05-20 12:58:46--  https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/start-box
u0_a1282@localhost ~> Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...   Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.                                            HTTP request sent, awaiting response... 200 OK
Length: 427 [text/plain]                                   Saving to: ‘start-box’
                                                           start-box      100%     427  --.-KB/s    in 0s

2023-05-20 12:58:46 (13.9 MB/s) - ‘start-box’ saved [427/427]

Error: file 'box86-64-rootfs-beta.tar.xz' does not exist.
                                                           Usage: proot-distro restore [FILENAME.TAR]

Restore distribution installation from a specified tarball. If
file name is not specified, it will be assumed that tarball is
being piped from stdin.

Options:

  --help               - Show this help information.

Archive compression is determined automatically from the file
extension. When archive content is piped it is expected that
data is not compressed.

Important note: there are no any sanity check being performed
on the supplied tarballs. Be careful when using this command as
data loss may happen when the wrong tarball was used.

Proot-Distro v3.11.0 by Termux.

I have tried clearing cache and data for Termux and trying again, but it's the same error.

Thanks for any help with this.

**Comment by Ilya114** [comment]
Well, I seems rootfs didnt download. Idk how to help

**Comment by JackJollimore** [comment]
> Well, I seems rootfs didnt download. Idk how to help

Thanks for your response as it helps me to narrow the problem slightly.

I downloaded box86-64-rootfs-beta.tar.xz manually from the release page.  Do you have any idea how to use it to finish the install?

**Comment by Ilya114** [comment]
`proot-distro restore /path/to/file`

**Comment by JackJollimore** [comment]
> `proot-distro restore /path/to/file`

That worked and now I am able to run start-box. It appears to be working as expected.


Thank you.
