### ISSUE TITLE
Just to be sure

### ISSUE THREAD

**Issue by SombraShadow** [Ilya114/Box64Droid#4]
![Screenshot_20230503-205745](https://user-images.githubusercontent.com/86113002/236083258-0d32b66a-a47f-4989-a5b9-d6c28be32f13.png)
In the termux it appeared that the installation was finished, but the space occupied by the termux is small, is that right?
(I haven't used it yet, just installed it right now)

**Comment by SombraShadow** [comment]
And also the start-x11 command doesn't work

**Comment by Coldboy195** [comment]
Try again.
![Screenshot_2023-05-04-08-03-39-194_com miui securitycenter](https://user-images.githubusercontent.com/105062195/236083983-40e8e96f-c748-48a0-9487-b103772e02a7.jpg)
