### ISSUE TITLE
Only dpad keys work with gamepad

### ISSUE THREAD

**Issue by InfamousKnight** [Ilya114/Box64Droid#40]
I'm using a USB adapter to use a Xbox one controller on my android.

Under controllers, it says no controller found. But the dpad keys seem to work.

**Comment by Ilya114** [comment]
Well, try add gamepad in Input Bridge. No more ideas

**Comment by InfamousKnight** [comment]
I clicked on input bridge in the termux-x11 app and a console window shoes up with nothing but installer title that last seemingly forever. I waited like an hour for something to show up.

Am I doing something wrong?

**Comment by SombraShadow** [comment]
> I clicked on input bridge in the termux-x11 app and a console window shoes up with nothing but installer title that last seemingly forever. I waited like an hour for something to show up.
> 
> Am I doing something wrong?

Bro,U Just need to leave this cmd window in the background ;-;
