### ISSUE TITLE
S20 fe snap qualcomm 865 problem.

### ISSUE THREAD

**Issue by MatteusSampaio** [Ilya114/Box64Droid#41]
To the developer:

S20 fe snap qualcomm 865 adreno android 13

BOX64 on Wine 8.0 no root

Problem: GPU CAPS Viewer doesn't  run Vulkan test
DirectX does not work with DXVK

Can NOT open DirectX files with DXVK.

- Termux version [e.g. 0.118]

**Comment by Ilya114** [comment]
I don't know
