### ISSUE TITLE
Error "prMovie::Open - Unable to connect pins"

### ISSUE THREAD

**Issue by Xiroichi** [Ilya114/Box64Droid#42]
Im trying to run  game Elminage Gothic. On logo/intro movie im getting this error "prMovie::Open - Unable to connect pins".
Intro movie is in wmv format.  I found this article https://www.protondb.com/app/291960, seams winetricks can help (winetricks wmp9 quartz devenum) i have not idea how to use it. How to fix this? probably use winetriks. Can you help with this issue?

**Comment by Ilya114** [comment]
Winetricks can he use from start menu
