### ISSUE TITLE
Hi, can you open source the way you compile turnip driver and setup DXVK ?

### ISSUE THREAD

**Issue by xDoge26** [Ilya114/Box64Droid#44]
Keeping it closed source is not cool buddy

**Comment by Ilya114** [comment]
It's not closed, but now can't compile T+Z without patches which not exist (I compiled when it's was possible). I don't remember compile command, probably this: `meson build -D platforms=x11,wayland -D gallium-drivers=swrast,virgl,zink -D vulkan-drivers=freedreno -D dri3=enabled  -D egl=enabled  -D gles2=enabled -D glvnd=true -D glx=dri  -D libunwind=disabled -D osmesa=true  -D shared-glapi=enabled -D microsoft-clc=disabled  -D valgrind=disabled --prefix /usr -D gles1=enabled -D freedreno-kmds=kgsl`, and `meson . build -Dgallium-va=disabled -Dgallium-drivers=zink,swrast -Ddri3=enabled -Dvulkan-drivers= -Dglx=xlib -Dplatforms=x11 -Dbuildtype=release`. You can see DXVK installation scripts in /opt/Resources (or Resources64)/DXVK (1.10.3-2.2)/DXVK (1.10.3-2.2).bat
