### ISSUE TITLE
torchlight 2 crashes upon receiving quest,(inc. 1st quest)

### ISSUE THREAD

**Issue by jurises99** [Ilya114/Box64Droid#45]
I tried to accept different quest, but it crashes upon receiving quest

this is the error message I received
wine: ../src/freedreno/common/freedreno_guardband.h:60: unsigned int fd_calc_guardband(float, float, bool): Assertion `gb_adj >= 1.0' failed.

**To reproduce**
use chroot box64 with pointer stick app and input bridge

**Screenshots**
can't upload screenshots, chrome crashes while uploading

 - Device: Mi 9t pro SD855
 - OS: a11 syberia OS
 - Termux version 0.118
 - X11 version : 1.02.10

**Comment by Ilya114** [comment]
Turnip issue, not Box64Droid

**Comment by jurises99** [comment]
how to update turnip?
