### ISSUE TITLE
Doesn't appear to work with Termux-X11 from Actions

### ISSUE THREAD

**Issue by parkerlreed** [Ilya114/Box64Droid#47]
**Describe the bug**

Latest Termux-X11 builds from Actions decoupled the client and server. Running termux-x11 in termux no longer automatically opens the client viewer, instead user has to open it themselves.

The usage within termux is just calling

```
termux-x11 :1
```

Which does NOT fork itself. Continues to run as a foreground process. 

And then running the client and proceeding to run something with the :1 DISPLAY socket.

When attempting to use Box64Droid (root/chroot) with the newer Termux-X11, nothing ever appears on the client display.

**To reproduce**

- Instal Termux-X11 from https://github.com/termux/termux-x11/actions
- Try running Box64 

**Screenshots**

If possible, make and add screenshots in spoiler to help explain your problem.

<details>

![Screenshot_20230602_162814_Termux](https://github.com/Ilya114/Box64Droid/assets/841440/357b0da3-9cd3-4505-861f-bbd0d4ef6eaa)

![Screenshot_20230602_162913_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/841440/879e72db-7e26-4756-8408-240dc9766b6d)

</details>

**Smartphone (please complete the following information):**

 - Device: Samsung Tab S8+
 - OS: Android 13
 - Termux version: 0.118.0+66a9495
 - Termux-X11 version: 1.02.7

**Comment by Ilya114** [comment]
1.02.07 not supported, use 1.02.10 from repo
