### ISSUE TITLE
시작시 오류문제

### ISSUE THREAD

**Issue by nicknjones** [Ilya114/Box64Droid#48]
Hello, after running termux
When entering the start-box for the first time, it comes out as a proot warning, and no wine is displayed on x11 Displayed by entering the second start-box I have to run it twice at all times, is there a solution

![Screenshot_20230604_160037_Gallery](https://github.com/Ilya114/Box64Droid/assets/135502365/10c7ca44-b709-49e4-bbbb-530be4531a7e)

**Comment by Ilya114** [comment]
use termux-x11 from repo and update Box64Droid

**Comment by nicknjones** [comment]
> repo에서 termux-x11을 사용하고 Box64Droid를 업데이트하십시오.

![Screenshot_20230605_161422_Gallery](https://github.com/Ilya114/Box64Droid/assets/135502365/5df40f00-791f-4a2a-b18b-fea4211efd48)

![Screenshot_20230605_162611_Gallery](https://github.com/Ilya114/Box64Droid/assets/135502365/56cc8408-7b11-47c2-854a-c500981d03e4)

Thanks for the answer. But after the update, the issue doesn't work out like in the picture. If you start box64droid after running termux for the first time, an error occurs. If you enter 9, come back to the terminal, and start box64droid, the error disappears as shown in the picture below I always have to repeat it twice
