### ISSUE TITLE
x11 blackscreen

### ISSUE THREAD

**Issue by Coldboy195** [Ilya114/Box64Droid#5]
Termux x11 blackscreen after I did one of list below:
1.Run winetrick
2.Dynarec 0
3.install PhysX
4.install VC C++

**Comment by seven768** [comment]
Termux-X11 connected now, but i have black screen too

**Comment by Ilya114** [comment]
> Termux x11 blackscreen after I did one of list below:
> 1.Run winetrick
> 2.Dynarec 0
> 3.install PhysX
> 4.install VC C++

I'm need to know why is don't starting. `start-box`->ctrl+c->`WINEPREFIX=.wine-amd64 box64 winecfg`



> Termux-X11 connected now, but i have black screen too

Don't enough info

**Comment by Coldboy195** [comment]
> I'm need to know why is don't starting. `start-box`->ctrl+c->`WINEPREFIX=.wine-amd64 box64 winecfg`

1 of 4 options make x11 doesn't appear TFM then blackscreen.
![Screenshot_2023-05-04-12-08-05-983_com termux](https://user-images.githubusercontent.com/105062195/236117035-6e07c628-cab4-4108-bcbc-10d7669028a9.jpg)

**Comment by Ilya114** [comment]
> 1 of 4 options make x11 doesn't appear TFM then blackscreen.

Oh, `/root/.wine-amd64` instead of `.wine-amd64`

**Comment by Coldboy195** [comment]
> Oh, `/root/.wine-amd64` instead of `.wine-amd64`

![Screenshot_2023-05-04-12-31-29-617_com termux](https://user-images.githubusercontent.com/105062195/236119498-c994c769-372b-4eba-bf89-8d1edf3bdb0c.jpg)
![Screenshot_2023-05-04-12-31-44-154_com termux x11](https://user-images.githubusercontent.com/105062195/236119519-3ff131b3-20a9-41a7-aec3-28e0126fc065.jpg)

**Comment by Ilya114** [comment]
> > Oh, `/root/.wine-amd64` instead of `.wine-amd64`
> 
> ![Screenshot_2023-05-04-12-31-29-617_com termux](https://user-images.githubusercontent.com/105062195/236119498-c994c769-372b-4eba-bf89-8d1edf3bdb0c.jpg) ![Screenshot_2023-05-04-12-31-44-154_com termux x11](https://user-images.githubusercontent.com/105062195/236119519-3ff131b3-20a9-41a7-aec3-28e0126fc065.jpg)

Seems Wine working normal. Try: `WINEPREFIX=/root/.wine-amd64 wine explorer /desktop=shell,800x600 /opt/TFM`

**Comment by Coldboy195** [comment]
> Seems Wine working normal. Try: `WINEPREFIX=/root/.wine-amd64 wine explorer /desktop=shell,800x600 /opt/TFM`
Command not found

**Comment by Ilya114** [comment]
> > Seems Wine working normal. Try: `WINEPREFIX=/root/.wine-amd64 wine explorer /desktop=shell,800x600 /opt/TFM`
> 
> Command not found

WINEPREFIX=/root/.wine-amd64 box64 wine explorer /desktop=shell,800x600 /opt/TFM

**Comment by Coldboy195** [comment]
> > > Seems Wine working normal. Try: `WINEPREFIX=/root/.wine-amd64 wine explorer /desktop=shell,800x600 /opt/TFM`
> > 
> > 
> > Command not found
> 
> WINEPREFIX=/root/.wine-amd64 box64 wine explorer /desktop=shell,800x600 /opt/TFM

![Uploading Screenshot_2023-05-04-13-10-11-143_com.termux.jpg…]()

**Comment by Coldboy195** [comment]
> > > Seems Wine working normal. Try: `WINEPREFIX=/root/.wine-amd64 wine explorer /desktop=shell,800x600 /opt/TFM`
> > 
> > 
> > Command not found
> 
> WINEPREFIX=/root/.wine-amd64 box64 wine explorer /desktop=shell,800x600 /opt/TFM

![Screenshot_2023-05-04-13-10-11-143_com termux](https://user-images.githubusercontent.com/105062195/236124755-234e4085-6fb4-46f6-bad5-eb7040a360da.jpg)

**Comment by Ilya114** [comment]
> > > > Seems Wine working normal. Try: `WINEPREFIX=/root/.wine-amd64 wine explorer /desktop=shell,800x600 /opt/TFM`
> > > 
> > > 
> > > Command not found
> > 
> > 
> > WINEPREFIX=/root/.wine-amd64 box64 wine explorer /desktop=shell,800x600 /opt/TFM
> 
> ![Screenshot_2023-05-04-13-10-11-143_com termux](https://user-images.githubusercontent.com/105062195/236124755-234e4085-6fb4-46f6-bad5-eb7040a360da.jpg)

Seems you need to reinstall Box64Droid
