### ISSUE TITLE
*It's not an issue, it's just a question*

### ISSUE THREAD

**Issue by SombraShadow** [Ilya114/Box64Droid#51]
I haven't updated in a long time the Box64droid in my phone cuz i have Android 11 (and I use the proot version).
Does box64droid (proot) work on Android 11 currently? If not, could you tell me why? (Or if there's a way to use it on Android 11).

**Comment by Ilya114** [comment]
Working on some ROMs, like MIUI. Not working in OneUI

**Comment by SombraShadow** [comment]
Hmm,ok but do you know if it works on Motorola?

**Comment by Ilya114** [comment]
No I don't have Motorola

**Comment by Ilya114** [comment]
Closing due a not active
