### ISSUE TITLE
A610 Turnip version 

### ISSUE THREAD

**Issue by nesper8** [Ilya114/Box64Droid#58]
Hi 
I'm making this issue to know the version of turnip you have provided for A610 cards so that it be used for other emulators like Yuzu and Skyline/Strato and those which support external drivers

It would really be appreciated if you can provide a meta.json yourself

Thank you very much

**Comment by Ilya114** [comment]
To use in Android you need compile it by Android SDK and NDK, you can try use https://github.com/ilhan-athn7/freedreno_turnip-CI/blob/main/turnip_builder.sh and change repo to https://gitlab.freedesktop.org/Danil/mesa/-/tree/freedreno/feature/a610

**Comment by nesper8** [comment]
Thank you 
Closing the issue now
