### ISSUE TITLE
can't chdir("/root/.") in the guest rootfs: No such file or directory

### ISSUE THREAD

**Issue by Abdulmalekak** [Ilya114/Box64Droid#59]
Hello
I start the command as in the instructions and installed the turnipA610 as in the gudie 
Then when I run the following error came in the picture below

**Comment by Abdulmalekak** [comment]
![Uploading Screenshot_20230607-081059_Termux.jpg…]()

**Comment by Ilya114** [comment]
One UI with Android 11 not supported, upgrade to 12
