### ISSUE TITLE
Java and program not install (exe)

### ISSUE THREAD

**Issue by TagasZX** [Ilya114/Box64Droid#61]
Hi, is there a way to put java? I'm trying to install 8, but error 1627 comes out. And I'm also trying to install some programs via exe, but they don't install either. Phone Asus rog 6 , snap 8 gen 1, 12 gb ram. Box64 - 64 bit

**Comment by Ilya114** [comment]
try with `BOX64_DYNAREC_STRONGMEM=1`

**Comment by TagasZX** [comment]
I'm sorry, how can this be used?

**Comment by revx0012** [comment]
He means box64 terminal mode, do `box64droid --start` and the terminal mode should be 9, that means type 9 and enter then type the command he gave to you

**Comment by Ilya114** [comment]
Closing due a not active
