### ISSUE TITLE
Black screen, unable to display

### ISSUE THREAD

**Issue by yazigegeda** [Ilya114/Box64Droid#62]
![Screenshot_2023-06-08-11-32-57-62_00df01c412509efb9bd6450c382822af](https://github.com/Ilya114/Box64Droid/assets/63853093/46176311-881a-4ab1-9cc3-6e0d1e195b74)

[Box64Droid.log](https://github.com/Ilya114/Box64Droid/files/11683804/Box64Droid.log)

`New Bridge brick at 0x10000 (size 0x1000)
New Bridge brick at 0x20000 (size 0x1000)
New Bridge brick at 0x30000 (size 0x1000)
Error: reading elf header of /opt/wine/bin/wine, try to launch using box86 instead
Dynarec log level is 1
Shows details of dlopen / dlsym /dlclose : Yes
Allow missing needed libs
Show Segfault signal even if a signal handler is present
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on AArch64 Processor rev 2 (aarch64)
 with 8 Cores
Params database has 22 entries
Using bash "/opt/box86_bash"
BOX86: Wine detected, WINEPRELOADRESERVE=""
New Bridge brick at 0x40000000 (size 0x1000)
New Bridge brick at 0x40010000 (size 0x1000)
New Bridge brick at 0x40020000 (size 0x1000)
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 47 Env var
Looking for /opt/wine/bin/wine
argv[1]="explorer"
argv[2]="/desktop=shell,800x600"
argv[3]="/opt/TFM"
Rename process to "wine"
New Bridge brick at 0x40030000 (size 0x1000)
Using native(wrapped) libdl.so.2
New Bridge brick at 0x40040000 (size 0x1000)
Using native(wrapped) libpthread.so.0
New Bridge brick at 0x40050000 (size 0x1000)
Using native(wrapped) libc.so.6
New Bridge brick at 0x40060000 (size 0x1000)
Using native(wrapped) ld-linux.so.2
New Bridge brick at 0x40070000 (size 0x1000)
Using native(wrapped) librt.so.1
BOX86: Call to dlopen("/opt/wine/bin/../lib/wine/i386-unix/ntdll.so"/0x63190888, 2)
Using emulated /opt/wine/bin/../lib/wine/i386-unix/ntdll.so
New Bridge brick at 0x40080000 (size 0x1000)
dlopen: New handle 0x1 (/opt/wine/bin/../lib/wine/i386-unix/ntdll.so), dlopened=1
Call to dlsym(0x1, "__wine_main")0xe806d030
Dynarec log level is 1
Shows details of dlopen / dlsym /dlclose : Yes
Allow missing needed libs
Show Segfault signal even if a signal handler is present
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on AArch64 Processor rev 2 (aarch64)
 with 8 Cores
Params database has 22 entries
Using bash "/opt/box86_bash"
BOX86: Wine detected, WINEPRELOADRESERVE=""
New Bridge brick at 0x40000000 (size 0x1000)
New Bridge brick at 0x40010000 (size 0x1000)
New Bridge brick at 0x40020000 (size 0x1000)
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 49 Env var
Looking for /opt/wine/bin/wine
argv[1]="explorer"
argv[2]="/desktop=shell,800x600"
argv[3]="/opt/TFM"
Rename process to "wine"
New Bridge brick at 0x40030000 (size 0x1000)
Using native(wrapped) libdl.so.2
New Bridge brick at 0x40040000 (size 0x1000)
Using native(wrapped) libpthread.so.0
New Bridge brick at 0x40050000 (size 0x1000)
Using native(wrapped) libc.so.6
New Bridge brick at 0x40060000 (size 0x1000)
Using native(wrapped) ld-linux.so.2
New Bridge brick at 0x40070000 (size 0x1000)
Using native(wrapped) librt.so.1
BOX86: Call to dlopen("/opt/wine/bin/../lib/wine/i386-unix/ntdll.so"/0x631908d0, 2)
Using emulated /opt/wine/bin/../lib/wine/i386-unix/ntdll.so
New Bridge brick at 0x40080000 (size 0x1000)
dlopen: New handle 0x1 (/opt/wine/bin/../lib/wine/i386-unix/ntdll.so), dlopened=1
Call to dlsym(0x1, "__wine_main")0xea2ed030
Call to dlsym((nil), "wine_main_preload_info")0x7d00300c
New Bridge brick at 0x10000 (size 0x1000)
New Bridge brick at 0x20000 (size 0x1000)
New Bridge brick at 0x30000 (size 0x1000)
New Bridge brick at 0x40000 (size 0x1000)
New Bridge brick at 0x50000 (size 0x1000)
New Bridge brick at 0x60000 (size 0x1000)
New Bridge brick at 0x70000 (size 0x1000)
New Bridge brick at 0x80000 (size 0x1000)
New Bridge brick at 0x90000 (size 0x1000)
New Bridge brick at 0xa0000 (size 0x1000)
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Warning: Unsupported libc Syscall 0x1C1 (449)
BOX86: Call to dlopen("/opt/wine/lib/wine/i386-unix/libwine.so.1"/0x631812a0, 2)
Using emulated /opt/wine/lib/wine/i386-unix/libwine.so.1
New Bridge brick at 0x40090000 (size 0x1000)
dlopen: New handle 0x2 (/opt/wine/lib/wine/i386-unix/libwine.so.1), dlopened=1
Call to dlsym(0x2, "wine_dll_set_callback")0x7c88d910
Call to dlsym(0x2, "__wine_main_argc")0x7ca0d22c
Call to dlsym(0x2, "__wine_main_argv")0x7ca0d228
Call to dlsym(0x2, "__wine_main_wargv")0x7ca0d224
Call to dlsym(0x2, "__wine_main_environ")0x7ca0d220
`

 - Device: [ OPPO a32]
 - OS: [e.g. Android 11]
 - Termux version [e.g. 0.118]

**Comment by Ilya114** [comment]
Install Turnip for Adreno 610 from repo, if still black screen so Android problem

**Comment by Shinra33** [comment]
Starting Box64Droid...
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
Mine shows that please help

**Comment by revx0012** [comment]
that means box64droid rootfs is not installed properly you will need to reinstall

**Comment by Ilya114** [comment]
Closing due a not active by creator of ticket
