### ISSUE TITLE
Termux x11 app shows not connected 

### ISSUE THREAD

**Issue by heeeeeeeeeeh** [Ilya114/Box64Droid#63]
**Describe the bug**

When starting box64droid, the termux x11 app shows not connected
Log:  
[Box64Droid.log](https://github.com/Ilya114/Box64Droid/files/11692905/Box64Droid.log)

**To reproduce**

- open termux
-  enter box64droid -- start
-  enter 1
- 4
- open termux x11 app 

**Screenshots**
![Screenshot_20230608-151555](https://github.com/Ilya114/Box64Droid/assets/90989842/160b032b-a482-4488-8d7a-27e7762e6f16)

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: Nokia x100
 - OS: Android 11
 - Termux version 0.118

**Comment by revx0012** [comment]
I think.... when you do `box64droid --start` and type `1` DONT TYPE ANY NUMBER!!! unless you want to exit
just ignore it don't type 4 or anything just go to termux-x11 app then it should connect

**Comment by Ilya114** [comment]
Closing due a not active
