### ISSUE TITLE
a question, is posible to use a gamepad and how to?

### ISSUE THREAD

**Issue by madmai** [Ilya114/Box64Droid#64]
**Describe the bug**

**To reproduce**

- Try '...' 

**gamepads**

a question, is posible to use a gamepad and how to?
<details>

can i use gamepad in box64 conected via bluetooth to android, i do but only works some buttons, thans in advance... i do but only works some buttons 
</detaills>

**Smartphone (please complete the following information):**

 - Device: [e.g. samsung tab s6 8/256gb]
 - OS: [e.g. Android 12]
 - Termux version [e.g. 0.118]

**Comment by Ilya114** [comment]
Try with Input Bridge

**Comment by madmai** [comment]
> Try with Input Bridge

i use gamepad bsp-d3 and diferents modes, but only axis, works on windows, buttons no works, button and axis works in android, but no works on bod64 wine, thanks for you fast reply

**Comment by Ilya114** [comment]
Closing due a not active
