### ISSUE TITLE
BLACK SCREEN 

### ISSUE THREAD

**Issue by Jder235** [Ilya114/Box64Droid#68]
![Screenshot_20230613-153541](https://github.com/Ilya114/Box64Droid/assets/136237136/5f7524b2-52fa-4b9e-a245-c34716066cc8)

**Box64droid.log**

- New Bridge brick at 0x10000 (size 0x1000) New Bridge brick at 0x20000 (size 0x1000) New Bridge brick at 0x30000 (size 0x1000) Error: reading elf header of /opt/wine/bin/wine, try to launch using box86 instead Dynarec log level is 1 Shows details of dlopen / dlsym /dlclose : Yes Allow missing needed libs Show Segfault signal even if a signal handler is present Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A53 with 6 Cores Params database has 22 entries Using bash "/opt/box86_bash" BOX86: Wine detected, WINEPRELOADRESERVE="" New Bridge brick at 0x40000000 (size 0x1000) New Bridge brick at 0x40010000 (size 0x1000) New Bridge brick at 0x40020000 (size 0x1000) Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/ Using default BOX86_PATH: ./:bin/ Counted 45 Env var Looking for /opt/wine/bin/wine argv[1]="explorer" argv[2]="/desktop=shell,800x600" argv[3]="/opt/TFM" Rename process to "wine" New Bridge brick at 0x40030000 (size 0x1000) Using native(wrapped) libdl.so.2 New Bridge brick at 0x40040000 (size 0x1000) Using native(wrapped) libpthread.so.0 New Bridge brick at 0x40050000 (size 0x1000) Using native(wrapped) libc.so.6 New Bridge brick at 0x40060000 (size 0x1000) Using native(wrapped) ld-linux.so.2 New Bridge brick at 0x40070000 (size 0x1000) Using native(wrapped) librt.so.1 BOX86: Call to dlopen("/opt/wine/bin/../lib/wine/i386-unix/ntdll.so"/0xf471f998, 2) Using emulated /opt/wine/bin/../lib/wine/i386-unix/ntdll.so New Bridge brick at 0x40080000 (size 0x1000) dlopen: New handle 0x1 (/opt/wine/bin/../lib/wine/i386-unix/ntdll.so), dlopened=1 Call to dlsym(0x1, "__wine_main")0xf4480030 Dynarec log level is 1 Shows details of dlopen / dlsym /dlclose : Yes Allow missing needed libs Show Segfault signal even if a signal handler is present Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A53 with 6 Cores Params database has 22 entries Using bash "/opt/box86_bash" BOX86: Wine detected, WINEPRELOADRESERVE="" New Bridge brick at 0x40000000 (size 0x1000) New Bridge brick at 0x40010000 (size 0x1000) New Bridge brick at 0x40020000 (size 0x1000) Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/ Using default BOX86_PATH: ./:bin/ Counted 47 Env var Looking for /opt/wine/bin/wine argv[1]="explorer" argv[2]="/desktop=shell,800x600" argv[3]="/opt/TFM" Rename process to "wine" New Bridge brick at 0x40030000 (size 0x1000) Using native(wrapped) libdl.so.2 New Bridge brick at 0x40040000 (size 0x1000) Using native(wrapped) libpthread.so.0 New Bridge brick at 0x40050000 (size 0x1000) Using native(wrapped) libc.so.6 New Bridge brick at 0x40060000 (size 0x1000) Using native(wrapped) ld-linux.so.2 New Bridge brick at 0x40070000 (size 0x1000) Using native(wrapped) librt.so.1 BOX86: Call to dlopen("/opt/wine/bin/../lib/wine/i386-unix/ntdll.so"/0xf323f9e0, 2) Using emulated /opt/wine/bin/../lib/wine/i386-unix/ntdll.so New Bridge brick at 0x40080000 (size 0x1000) dlopen: New handle 0x1 (/opt/wine/bin/../lib/wine/i386-unix/ntdll.so), dlopened=1 Call to dlsym(0x1, "__wine_main")0xf2fa0030 Call to dlsym((nil), "wine_main_preload_info")0x7d00300c wine: cannot use directory /root/.wine : Function not implemented 

**Screenshots**

If possible, make and add screenshots in spoiler to help explain your problem.

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: [e.g. sharp M05(adreno 505)
/]
 - OS: [e.g. Android 8]
 - Termux version [e.g. 0.118]

**Comment by Ilya114** [comment]
Android 8 not supported
