### ISSUE TITLE
Game Crashes Emulation/Termux

### ISSUE THREAD

**Issue by morealternative** [Ilya114/Box64Droid#69]
**Describe the bug**

Game: Crysis Warhead Steam Version (Super Low Settings)

Case 1 - Emulation/Termux Crash:
When game loads level, im just in termux x11 and termux closes and x11 shows disconnection

Case 2 - Game Just Closes
Same As Case 1 but instead of waiting in x11, im waiting in termux and game just closes

**To reproduce**

- I dont know, i just installed and started game it was working before but for some reason now it doesnt, maybe some package outside distro does it?

**Screenshots**
Proof that game **was** working:
![Screenshot_2023-05-31-11-10-39-456_com termux x11](https://github.com/Ilya114/Box64Droid/assets/89259624/ff323180-8a88-4e49-847f-f90d27f039e4)
![Screenshot_2023-06-06-17-59-08-281_com termux x11](https://github.com/Ilya114/Box64Droid/assets/89259624/f2989fbf-617f-4be3-8e0d-f6a566b97993)

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: Xiaomi Mi 11 Lite 5G 8GB Ram 
 - OS: Android 12
 - Termux version: 0.118.0

Box64Droid Log:
[Box64Droid.log](https://github.com/Ilya114/Box64Droid/files/11738658/Box64Droid.log)

Game Log:
[Game.log](https://github.com/Ilya114/Box64Droid/files/11738666/Game.log)

**Comment by Ilya114** [comment]
I'm dont know solution
