### ISSUE TITLE
box64

### ISSUE THREAD

**Issue by revx0012** [Ilya114/Box64Droid#70]
**Describe the bug**

So, when i try to start box64droid it's black screen so i decided to do debug mode then suddenly on the termux-x11 said im not connected well i didn't care about that so I went to my file manager and i saw the text saying: "taskset: failed to execute box64: No such file or directory" what does this mean anyway?? box64 not found.. super weird!

**Screenshots**
i couldn't put screenshot because of crash, heres in a text instead:
`Wine will be start with debug info, log will be save in /sdcard/Box64Droid.log. Open issue in Github and send /sdcard/Box64Droid.log if you have black screen or crashed apps/games
To exit from Box64Droid press type '1' then press Enter`

**Smartphone (please complete the following information):**

 - Device: [Samsung Galaxy A32]
 - OS: [Android 13]
 - Termux version [0.118.0]

**Comment by Ilya114** [comment]
Reinstall

**Comment by revx0012** [comment]
Thank you guys, it fixed my issue!
