### ISSUE TITLE
Installed without any problem but couldn't launch anything

### ISSUE THREAD

**Issue by WanderingMurchalo** [Ilya114/Box64Droid#72]
Logo window turns black when trying to launch (not to install) any game. Everything else keeps working.
Is there something I can do to cope with such a problem?

 - Device: Galaxy S22Ultra (Gen1)
 - OS: Android 13
 - Termux version 0.118

From log:
BOX86: Call to dlopen("/opt/wine/lib/wine/i386-unix/concrt140.so"/0x632b47c8, 2)

Warning: Cannot dlopen("/opt/wine/lib/wine/i386-unix/concrt140.so"/0x632b47c8, 2)

0x41123e: Dynarec stopped @ dynarec0F0 (/root/box86/src/dynarec/dynarec_arm_0f.c:2716) because of Opcode 0F 01 D0 89 45 EC 89 55 F0 8B 45 EC 8B 4D F0

![Screenshot_20230615_151117_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/136741093/6d631f9b-d405-4baa-91c7-8e4f275ae948)

**Comment by Ilya114** [comment]
I dont know solution
