### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by revx0012** [Ilya114/Box64Droid#73]
How can i run box64droid in vnc? is it possible? if yes then how can i do that because it's easier in vnc. the termux-x11 i can't even drag windows/tabs i think?
Please just tell me if it's possible or not.

**Comment by Ilya114** [comment]
I'm not like VNC, officially it not supported

**Comment by revx0012** [comment]
well well well, i actually edited something and it worked.. i ran box64droid in vnc! so how is it not supported? lol!

**Comment by revx0012** [comment]
same thing with rdp

**Comment by revx0012** [comment]
(if you know what that is though)
