### ISSUE TITLE
New issue 

### ISSUE THREAD

**Issue by trex-coder** [Ilya114/Box64Droid#74]
![Screenshot_2023-06-16-13-51-10-732_com termux](https://github.com/Ilya114/Box64Droid/assets/110154601/02746d3b-9afd-42db-beff-489a7ad82c30)
![Screenshot_2023-06-16-13-45-29-537_com termux](https://github.com/Ilya114/Box64Droid/assets/110154601/4f8d5a32-f4f6-4b0e-ab89-399c3da2b40c)

**Comment by Ilya114** [comment]
Update Termux-X11
