### ISSUE TITLE
Apt update fails, fix inside this issue.

### ISSUE THREAD

**Issue by Dr4kzor** [Ilya114/Box64Droid#75]
Execute box64droid --start
run to terminal mode,
run apt update

all downloads will fail with temporary unavailable.

To fix this edit /etc/passwd,
this can be edited from outside the chroot or proot by navigating to ubuntu installation folder mannually.

on the "/etc/passwd/' file look for "_apt", here there will be a number similar to :65432::, change it to 3003, your end result should look like this: _apt:x:100:3003::/nonexistent:/usr/sbin/nologin

after this login to box64droid terminal mode

run apt clean and exit

restart  box64droid in terminal mode and try to run "apt  update", it should now work :)

This was run on a Xiaomi pad 5 pro with ArrowOS 13.1 rooted, installeda and executed root version (works well, able to use this with Aseprite, Godot game editor both 3.5 and 4.0.3, also tested an old game called Starscape and runs like a charm)

I also have a question, am I also able  to run apps on Linux (linux app) with this chroot and keep the hardware acceleration? Or does this only work inside Wine? Thank you for your work :)

**Comment by Ilya114** [comment]
Because Turnip+Zink compiled for Linux Arm64 and armhf, Linux apps will work with 3D acceleration also

**Comment by Dr4kzor** [comment]
I reinstalled everything from start to document how to fix the apt update issue.

So in order to fix the temporary unavailable thingy first you need to enter the terminal in chroot by using option 9 from box64droid --start menu.

after this edit the file /etc/passwd,

on the "/etc/passwd/' file look for "_apt", here there will be a number similar to :65432::, change it to 3003, your end result should look like this: _apt::100:**3003**::/nonexistent:/usr/sbin/nologin

now we need to fix the permission of /tmp/
run chmod 777 /tmp/

and now apt update should work as normally

**Comment by Ilya114** [comment]
Closing due a not active
