### ISSUE TITLE
Chroot Linux with xfce4 fails to get hardware accel on second run (works ok first run) With solution to problem

### ISSUE THREAD

**Issue by Dr4kzor** [Ilya114/Box64Droid#76]
This is only for users running the Root version

**Run box64droid in terminal mode (option 9)**
apt install xfce4

if you cannot install, you need to fix your apt update issues:
problem with /etc/passwd (_apt line needs to be edited, change the number 665574 or whatever you have for 3003 and leave the rest intact)
problem with /tmp/ permissions (chmod 777 /tmp/ )
Or read here [Fixing apt update](https://github.com/Ilya114/Box64Droid/issues/75)

Now you should have **xfce4 installed**, to run simply **execute xfce4-session** and you should see an output on termux-x11.

Now to start the low fps problem close everything and restart xfce4, notice that now at the top left corner of the screen you can see fps values, this means we are running the **xfce4 with incorrect configs** (auto created after first sucessfull hardware accell run)

To **fix this low fps issue** we need to **edit the created xfce4 config file**.

Edit the file  **~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml** 
nano ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml 

**locate the line:**

`<property name="use_compositing" type="bool" value="true"/>`

**and change the value to false:**

`<property name="use_compositing" type="bool" value="false"/>`

to save changes press Ctrl+x and y

now you can **exit and restart chroot.**
We have now fixed the problem with the Harware  Acceleration on every startup  of Linux
Now to run Linux UI with hardware accel **simply run start xfce4-session**!

**Smartphone (please complete the following information):**

 - Device: [Xiaomi pad 5  pro 5G] (snapdragon870)
 - OS: [ArrowOS 13.1 - Android 13]
 - Termux version [0.118]

**Comment by Ilya114** [comment]
Which line exactly?

**Comment by Dr4kzor** [comment]
Sry the line code was not displaying properly, it now shows its `<property name="use_compositing" type="bool" value="true"/>`
chage it to false.

**Comment by Ilya114** [comment]
I also fixed tmp

**Comment by Ilya114** [comment]
Closing due a not active
