### ISSUE TITLE
Why is it that after I write box64droid --start it immediately says command not found?

### ISSUE THREAD

**Issue by Gibran235** [Ilya114/Box64Droid#78]
![Screenshot_20230619_121025](https://github.com/Ilya114/Box64Droid/assets/137026885/f6027ce3-c6ce-402e-842d-c41b9d4c5459)
**Describe the bug**

**To reproduce**

- Try '...' 

**Screenshots**

If possible, make and add screenshots in spoiler to help explain your problem.

<details>

</details>

**Smartphone (please complete the following information):**

 - Device: [e.g. Xiaomi POCO X3 Pro]
 - OS: [e.g. Android 13]
 - Termux version [e.g. 0.118]

**Comment by Ilya114** [comment]
Clear Termux data and install again

**Comment by Ilya114** [comment]
Closing due a not active
