### ISSUE TITLE
Why are there strange processes running (maybe spyware)??

### ISSUE THREAD

**Issue by Dr4kzor** [Ilya114/Box64Droid#83]
Why is ssh-agent -s running on background (and it is never closed remaining open forever untill reboot of phone or by manually killing it)? And why is rpcss, TFM and tabtip running inside wine?
It's screaming spyware to me... Anyone know why these are running?

So apparently ssh-agent by default starts when xfce4 starts and it's located at /etc/X11/Xsession.d/90x11-common_ssh-agent,
It seems to be related to xfce4 itself but always fails to exit in chroot mode so a manual killall ssh-agent is needed

**Comment by Ilya114** [comment]
1. Ssh not installed in Box64Droid in box, so probably your packages can run it. https://linux.die.net/man/1/ssh-agent here you can read what is ssh-agent.
2. rpcss, tabtip and TFM is a wine process, idk where is problems
