### ISSUE TITLE
Box64 not loading 

### ISSUE THREAD

**Issue by Majtan** [Ilya114/Box64Droid#9]
Thought I'd try the reduced size latest beta update only box86 seems to work and box64 has totally stopped only shows black screen in termux x11.

The installed size now is 4.65 gb clean install
Before it was 6.45 gb with some redist installed 

Maybe something missing in box64 side I've re installed several times even removing both apks and all data 

Please fix.. or is there any way to go back one version?  Was working great there I had 64bit game ender Lillie's working 30+ fps dxvk 2.1 with 4 cores only gripe was cutscenes didn't play thought it might be a redist/ netframeworks install issue hence I deleted old install to try new now I'm stuck maybe it is just beta and I have to wait some more?

Thanks in advance  and thanks for all the work you've done so far amazing b4bit games on Android hope it keeps getting better

**Comment by Majtan** [comment]
Btw I used proot script and I have snap 888+ andreno 660

**Comment by stredohori1** [comment]
For me also only black screen in Termux-X11. I tried update system, update boxes and change Wine to 8.2-staging-tkg. Now I'm stuck on Wine prefix update for 20 min now, no change.
![Screenshot_20230507_064802](https://user-images.githubusercontent.com/130311769/236658207-b4b65c32-1652-4af5-ba87-f99930903947.jpg)

**Comment by Majtan** [comment]
I can't even get into box64 anymore only box86 works, it's strange it happened before the previous update too when project moved to Box64Droid but was fixed after an update now when the new script arrived and the smaller archive size rootfs it only seems to load box86 and the cntrl c 1 option to stop box64 doesn't work either strangely enough only typing 1 works but on box86 it seems to work

**Comment by Ilya114** [comment]
Will see later

**Comment by Ilya114** [comment]
> Now I'm stuck on Wine prefix update for 20 min now, no change.

Due a already linked D: drive, as I said will update rootfs with link D: drive after creating prefix

**Comment by stredohori1** [comment]
> Due a already linked D: drive, as I said will update rootfs with link D: drive after creating prefix
To add D: drive manually isn't a problem to me I always do it so but this also will be convenient ;-)

**Comment by Ilya114** [comment]
Should be fixed, try again

**Comment by Brucelee23** [comment]
it keeps crashing from ternut 11 on my phone

**Comment by stredohori1** [comment]
> Should be fixed, try again

Changed wine immediately and it works, 
![Screenshot_20230507_124202](https://user-images.githubusercontent.com/130311769/236672851-65b278c2-d299-4ab0-afb3-0fadacdaed2c.jpg)
drive D: too👍

**Comment by Ilya114** [comment]
> Changed wine immediately and it works,

Today will update again with updated box86 and box64 + with less archive size and fix the warning when changing the Wine version...

**Comment by Ilya114** [comment]
I seems main problem solved, so can close
