### ISSUE TITLE
Horrible FPS in 2d game, HELP!

### ISSUE THREAD

**Issue by YorkviskBR** [Ilya114/Box64Droid#95]
Well, I was testing the game Battle Brothers, it's a completely 2d and light game, minimum requirements:
CCPU SPEED: 1.2 Ghz
RAM: 1024 MB
VIDEO CARD: OpenGL 3.3 compatible video card with 512MB of memory
DEDICATED VIDEO RAM: 512 MB
Windows XP, Windows Vista, Windows 7, Windows 8, Windows 10
FREE DISK SPACE: 1500 MB

Even so, it ran very poorly on my device, which isn't even bad:
Samsung Galaxy S10 (US)
SD855 / ADRENO 640 / 8GB RAM

I tried using DXVK (all versions), but it didn't work. I switched to wined3d and it improved performance a little.

**NATIVE VERSION**

 I tried EESYNC and mesa_glthread=True but it didn't work either, performance is still poor

In battle and on the world map especially, the game's performance is horrible.
![Screenshot_20240108-091715_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/155840080/73047952-dd24-43c5-8445-dc575ae94378)
![Screenshot_20240108-115626_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/155840080/32c9391f-1c38-4a1d-94ba-f689009ccd3f)
![Screenshot_20240108-120058_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/155840080/cf451b97-6af1-4b98-b3e7-2edf6abe79ba)
![Screenshot_20240108-120152_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/155840080/2e845ff1-6648-4260-8862-7ca5b810f9bd)
![Screenshot_20240108-120205_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/155840080/d96fc938-d5f4-4b82-8411-d578aa012f10)

**Comment by Ilya114** [comment]
Box64Droid is not for 2D games, you can try use some emulator with 2d renderer

**Comment by zingtian** [comment]
> Box64Droid is not for 2D games, you can try use some emulator with 2d renderer

Hello can you please guide or give some example of emulators with 2d renderer. I was shocked to find my sd 888 not being able to run minimalistic games.

**Comment by YorkviskBR** [comment]
> > Box64Droid is not for 2D games, you can try use some emulator with 2d renderer
> 
> Hello can you please guide or give some example of emulators with 2d renderer. I was shocked to find my sd 888 not being able to run minimalistic games.

Man, me too, it's crazy to think that a 2d game is heavier than GTA V to emulate

**Comment by zingtian** [comment]
> > > Box64Droid is not for 2D games, you can try use some emulator with 2d renderer
> > 
> > 
> > Hello can you please guide or give some example of emulators with 2d renderer. I was shocked to find my sd 888 not being able to run minimalistic games.
> 
> Man, me too, it's crazy to think that a 2d game is heavier than GTA V to emuli 

I have no knowledge of pc emulators and idk after testing out all version of dxvk and wine d3d my game is not even opening , it just freezes the whole termux:x11
![Screenshot_20240109_201054_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/123048131/1f8652fc-a075-422b-bda5-bb2c6a4e8c65)

**Comment by YorkviskBR** [comment]
> > > > Box64Droid não é para jogos 2D, você pode tentar usar algum emulador com renderizador 2d
> > > 
> > > 
> > > Olá você pode por favor orientar ou dar algum exemplo de emuladores com renderizador 2d. Fiquei chocado ao descobrir que meu sd 888 não era capaz de executar jogos minimalistas.
> > 
> > 
> > Cara, eu também, é loucura pensar que um jogo 2d é mais pesado que GTA V para emuli
> 
> Eu não tenho conhecimento de emuladores de pc e idk depois de testar toda a versão do dxvk e vinho d3d meu jogo não está mesmo abrindo , ele apenas congela todo o termux:x11. Se você tem algum guia ou ajuda para oferecer. Vou levar tudo. ![Captura de tela_20240109_201054_TermuxX11](https://private-user-images.githubusercontent.com/123048131/295240081-1f8652fc-a075-422b-bda5-bb2c6a4e8c65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTM5NTAsIm5iZiI6MTcwNDgxMzY1MCwicGF0aCI6Ii8xMjMwNDgxMzEvMjk1MjQwMDgxLTFmODY1MmZjLWEwNzUtNDIyYi1iZGE1LWJiMmM2YTRlOGM2NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNTIwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTQ4OGY1NDEwZmNkZjRhY2I1M2E4MTE0ZGFmNjc5MzliYjBiODI3NTRiOWY5NzU2YWI0ZDU1MTUzYjQ4MTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.squ5o-4sozZS_M4uVnCTUzwt02FEK2Z_7_clkPZmZdg)

That's strange, my friend, because all 3d games should work fine. Try watching a tutorial on YouTube, before that, uninstall termux and install it again, and install the native box64droid, maybe it was a bug. Better re-install
