### ISSUE TITLE
The games donot work on full screeeeen 

### ISSUE THREAD

**Issue by Vhilooooo17111** [Ilya114/Box64Droid#99]
Hiiiiii the games don't work on full screen I need to fix this prooooooblem
![Screenshot_٢٠٢٤٠١١٩-٠٢٠٤٢٦_TermuxX11](https://github.com/Ilya114/Box64Droid/assets/157109512/59281354-a764-4ccf-8952-c9fa2b0cc622)

**Comment by Ilya114** [comment]
Set in Termux-X11 same resolution as in Box64Droid

**Comment by Vhilooooo17111** [comment]
Bro I did it but not work the emulator run on full screen but when I try to run games it's not work on full screen

**Comment by Vhilooooo17111** [comment]
> Set in Termux-X11 same resolution as in Box64Droid

Brooke how to fix this prooooblem
